### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by kulte** [avadev/AvaTax-REST-V2-Ruby-SDK#10]
How do I create a transaction? Why did you decide to provide so little documentation?

**Comment by kulte** [comment]
I'm calling

```ruby
AvaTax::Client.new(logger: true).create_transaction(...)
```

where `...` is a Hash of what I've been able to piece together from your total lack of documentation what I need to pass. I'm getting back

```
*** ArgumentError Exception: wrong number of arguments (given 3, expected 1..2)
```

I looked at the method signature and this doesn't make sense. Please help!

**Comment by kulte** [comment]
So the answer to my question of "does this work at all" seems to unfortunately be "no". Do you see that on this line

https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/0b8a72887e8e2f19c84e6838dbae2b81178c8e33/lib/avatax/client/transactions.rb#L221

you are calling post and passing in 3 arguments, however you've defined the `#post` method on `Request` to accept 2 arguments.

https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/0b8a72887e8e2f19c84e6838dbae2b81178c8e33/lib/avatax/request.rb#L10

Do you see how this completely breaks anyones ability to perform the most basic functionality of this library?

**Comment by marcus** [comment]
Thanks for your feedback @kulte . I'm looking into the issues you've mentioned and should have an update shortly.

**Comment by marcus** [comment]
In the meantime, if you'd like to see full documentation you can run:
```
npm install -g yard
yard doc
yard server
```
From the project root. Then browse to http://localhost:8808.

**Comment by key88sf** [comment]
@marcus Is there any update on this?

**Comment by marcus** [comment]
@key88sf please try the release from today.
