### ISSUE TITLE
Latest commits break gem again

### ISSUE THREAD

**Issue by tmilker** [avadev/AvaTax-REST-V2-Ruby-SDK#13]
commit 636ed9d0e93bb58cdf40d95e5957750c6ef81812 and on from Sep 8th once again put the gem in a broken state.  post() is not being called correctly.

**Comment by tmilker** [comment]
It looks like the documentation updates to the Transactions module also accidentally reverted my fixes for the use of post.  Other parts of the commit use post correctly, so someone didn't merge before committing and pushing their fork.

**Comment by tmilker** [comment]
Actually it appears like it's more complex than that.  I don't have time to dig deeper into this right now though.

**Comment by marcus** [comment]
@tmilker can you try the release from today? I believe it should resolve your problems. If not, pls comment and reopen this.
