### ISSUE TITLE
Authenticating via account ID and license key

### ISSUE THREAD

**Issue by SophiaLWu** [avadev/AvaTax-REST-V2-Ruby-SDK#27]
Is it possible to authenticate via Account ID/license key using this SDK? 

I don't think adding it as a header to the `connection_options` argument works because the options are merged instead of deep merged and would overwrite the initial headers [here]( https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/eb7c20b8e925a3d682f6414207e298e519e0a549/lib/avatax/connection.rb#L21).

I don't think this works:
```
client = AvaTax::Client.new(connection_options: { :headers => { 'Authorization' => 'Basic MjAwMDI2NjEyODo3MUIwQTg3QjhGNzNFQ0M5' } })
```

Do you have any suggestions? I definitely could have just misread something.

Thanks!

**Comment by han8909227** [comment]
Hi @SophiaLWu 
In AvaTax both username/password pair and accound_id/license_key pair can be used as a way of authenticating a user, meaning 
`AvaTax.configure do |config|
  begin
    config.username = credentials['username']
    config.password = credentials['password']
end`
is the same as 
`AvaTax.configure do |config|
  begin
    config.username = credentials['account_id']
    config.password = credentials['license_key']
end`

They both will be Base64 hashed by the request module, and both are can be validated by our API

**Comment by SophiaLWu** [comment]
Ah that worked perfectly. Sorry about the confusion!
