### ISSUE TITLE
Estimating And Commiting TaxInvoices?

### ISSUE THREAD

**Issue by braidn** [avadev/AvaTax-REST-V2-Ruby-SDK#3]
Hey all!

I am working on an integration for an existing Avalara customer and was wondering how ready this API is and or how far out do you all think a V1 is? What I mainly have to do is calculate tax which looks like is doable through https://github.com/avadev/AvaTax-Calc-REST-Ruby . 

I guess my question is, should I start tracking the master here or keep to the old gem? Thank you.

**Comment by marcus** [comment]
Hi @braidn, you can consider the version of this gem released yesterday to be ready for use.
