### ISSUE TITLE
Getting UnknownNexusError on creating a nexus

### ISSUE THREAD

**Issue by Abhimaropost** [avadev/AvaTax-REST-V2-Ruby-SDK#43]
I'm getting UnknownNexusError on creating a nexus. Below is the data, i'm sending in body:
{
    "country": "CN",
    "region": "AB",
    "jurisTypeId": "STA",
    "jurisdictionTypeId": "State",
    "jurisCode": "AB",
    "jurisName": "ALBERTA"  
}

**Comment by marcus** [comment]
This error is not related to the ruby gem, it's an avatax usage issue. Please use the Avalara developer forums, reference the API docs, or contact support.
