### ISSUE TITLE
Avatax::Request dropping querystring params on post

### ISSUE THREAD

**Issue by oehlschl** [avadev/AvaTax-REST-V2-Ruby-SDK#45]
FYI, it looks like the `options` param passed to `AvaTax::Request#request` is effectively ignored in the case of PUT and POST requests. It might be more specific than that (say, limited to a specific Faraday adapter), but it's reproducible and pretty clear what's going on.

**Context:**

We noticed this after getting a "Please specify DocumentType parameter" response error despite specifying one in a `refund_transaction` call:

```ruby
payload = {
  refundTransactionCode: transaction_code,
  refundDate: Date.today.to_s,
  refundType: 'Full'
}
resp = client.refund_transaction(company_code, transaction_code, payload, {useTaxDateOverride: true, documentType: 'SalesInvoice'})
```

That call fails unexpectedly with the error:
```json
{
  "error": {
    "code": "DocumentCodeConflict",
    "message": "Please specify DocumentType parameter",
    "target": "HttpRequest",
    "details": [
      {
        "code": "DocumentCodeConflict",
        "number": 303,
        "message": "Please specify DocumentType parameter",
        "description": "This API applies to a single document, but multiple documents exist for company 'XXXXXXXXX' and code '15151515'.  Please provide the DocumentType parameter to distinguish between them.",
        "faultCode": "Client",
        "helpLink": "http://developer.avalara.com/avatax/errors/DocumentCodeConflict",
        "severity": "Error"
      }
    ]
  }
}
```

**Diagnosis:**

It looks like that call creates the following Faraday request object:
```
<struct Faraday::Request
method=:post,
path="/api/v2/companies/XXXXXXX/transactions/15151515/refund?useTaxDateOverride=true&documentType=SalesInvoice",
params={},
headers={"Accept"=>"application/json; charset=utf-8", "User-Agent"=>"AvaTax Ruby Gem 18.10.3", "X-Avalara-Client"=>"XXXXXXXXXXX", "Authorization"=>"Basic XXXXXXXX", "Content-Type"=>"application/json"},
body="{\"refundTransactionCode\":15151515,\"refundDate\":\"2019-02-04\",\"refundType\":\"Full\"}",
options=#<Faraday::RequestOptions (empty)
>
```

At some point, however, the `params` hash overwrites the params from the URL before it gets issued. This is reproducible by calling `request.to_env(connection)`:

```
<Faraday::Env
@method=:post
@body="{\"refundTransactionCode\":15151515,\"refundDate\":\"2019-02-04\",\"refundType\":\"Full\"}"
@url=#<URI::HTTPS https://sandbox-rest.avatax.com/api/v2/companies/XXXXX/transactions/15151515/refund>
@request=#<Faraday::RequestOptions (empty)>
@request_headers={"Accept"=>"application/json; charset=utf-8", "User-Agent"=>"AvaTax Ruby Gem 18.10.3","X-Avalara-Client"=>"XXXXXXXXXXX", "Authorization"=>"Basic XXXXXXXX", "Content-Type"=>"application/json"}
@ssl=#<Faraday::SSLOptions (empty)>
>
```

(This happens here: https://github.com/lostisland/faraday/blob/e6311bd286de8df1a585b2d5a1eeb150f6d067bf/lib/faraday/connection.rb#L417)

Accordingly, the `documentType` is not longer anywhere in the request even though it was present in the original `options` hash.

**Solution:**

After some investigation, it looks like the `request.path=` call used in the PUT/POST case... 
https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/51144efe8f063b7ecf76aef8c90021708fc055c1/lib/avatax/request.rb#L29
...should probably just be `request.url`, which correctly sets both `request.path` and `request.params`:

https://github.com/lostisland/faraday/blob/f08a985bd1dc380ed2d9839f1103318e2fad5f8b/lib/faraday/request.rb#L48

Note that after updating this locally, the querystring params are contained in the URL as we expect:

```
<Faraday::Env
@method=:post
@body="{\"refundTransactionCode\":15151515,\"refundDate\":\"2019-02-04\",\"refundType\":\"Full\"}"
@url=#<URI::HTTPS https://sandbox-rest.avatax.com/api/v2/companies/XXXXXXX/transactions/15151515/refund?documentType=SalesInvoice&useTaxDateOverride=true>
@request=#<Faraday::RequestOptions (empty)>
@request_headers={"Accept"=>"application/json; charset=utf-8", "User-Agent"=>"AvaTax Ruby Gem 18.10.3","X-Avalara-Client"=>"XXXXXXXXXXX", "Authorization"=>"Basic XXXXXXXX", "Content-Type"=>"application/json"}
@ssl=#<Faraday::SSLOptions (empty)>
>
```

I'll open up a PR for this change, though it's pretty fundamental and I'm therefore not confident from the test coverage alone. Would love a sanity check from someone more familiar with the this lib.

Thanks!

**Comment by marcus** [comment]
Thank you for the detailed bug report. This will be fixed in our next release.

**Comment by oehlschl** [comment]
Thanks for the quick merge and for @brianlu365 for identifying this!
