### ISSUE TITLE
Gem is non-functional as-is

### ISSUE THREAD

**Issue by tmilker** [avadev/AvaTax-REST-V2-Ruby-SDK#6]
Multiple issues with this gem that make it non-functional, as-is:

- Client::Transactions methods add_lines, create_or_adjust_transaction, create_transaction, delete_lines, and refund_transaction try to use post() incorrectly, it doesn't take both a model argument and options.
- Incorrect encoding used with Faraday request.

Other issues:

- Documentation implies that model should be an object, but request() code is written expecting a JSON string.  Request should call to_json before setting the body or documentation should be updated.

**Comment by tmilker** [comment]
If anyone cares, my fork at https://github.com/tmilker/AvaTax-REST-V2-Ruby-SDK has a running set of commits to fix these issues and others.  It is starting to get a little opinionated(BigDecimals instead of floats, for example), so cherry pick what you like.

**Comment by marcus** [comment]
Hey, I just saw this issue - would you mind opening a PR and I'll get your changes merged in?

**Comment by marcus** [comment]
Actually @tmilker I went ahead and cherry-picked your commits and pushed a new version of the gem. Thanks!
