### ISSUE TITLE
Create an eCommerce token endpoint

### ISSUE THREAD

**Issue by ChaelCodes** [avadev/AvaTax-REST-V2-Ruby-SDK#83]
# Description
One of the routes in the REST API documentation is [CreateECommerceToken](https://developer.avalara.com/api-reference/avatax/rest/v2/methods/ECommerceToken/CreateECommerceToken/). I can't fine this route in the source files of this gem. Is it unimplemented? Is it called something else? Is it undocumented?

# Solution
Add or document ECommerceToken calls in lib/avatax/client/

**Comment by crstamps2** [comment]
It appears this was completed very recently. 

https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/master/lib/avatax/client/ecommercetoken.rb

**Comment by ChaelCodes** [comment]
Great!
