### ISSUE TITLE
Should release 20.8.0 be named 20.9.0?

### ISSUE THREAD

**Issue by tartakynov** [avadev/AvaTax-REST-V2-Ruby-SDK#85]
In Github the latest release is named 20.8.0 but in Rubygems it's 20.9.0 and even in `version.rb` of 20.8.0
https://github.com/avadev/AvaTax-REST-V2-Ruby-SDK/blob/7dc6e38888863566a39a43db093bdeb72dd6b2f6/lib/avatax/version.rb#L2

So it's a little bit confusing

**Comment by crstamps2** [comment]
I also noticed this today. 20.8.0 introduced the ecommerce token stuff, but that version of the gem is not on rubygems.org.
