### ISSUE TITLE
Ruby 2.7 compatibility

### ISSUE THREAD

**Issue by AlecRust** [avadev/AvaTax-REST-V2-Ruby-SDK#90]
When I run tests which use this gem after upgrading Ruby 2.6.6 -> 2.7.2 I get a lot of these warnings in my output:

```
/Users/alec/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/avatax-20.9.0/lib/avatax/request.rb:31: warning: URI.escape is obsolete
```

**Comment by daralbrecht** [comment]
Any chance of resolving this problem? I would like to switch to Ruby 3.0 but this becomes a blocker for me :/

**Comment by vinodlala** [comment]
Same here.

**Comment by AlecRust** [comment]
@shilpakhanal @shilpa-khanal any chance you could review #100 which fixes this?

**Comment by AlecRust** [comment]
This is done, we're running this gem on Ruby 3.1 successfully. Thanks again!
